// AUTO-GENERATED by `npm run generate`. Do not edit by hand.
// Source of truth: .env + content/articles/**/*.json
import type { Article } from "@/features/articles/types/article";
import type { SiteConfig } from "@/features/articles/types/site";

import site from "./site.json";
import a0 from "./articles/id/cara-memilih-villa-di-bali.json";
import a1 from "./articles/en/how-to-choose-a-villa-in-bali.json";

export const siteConfig: SiteConfig = site;

/** Published articles per language code, newest first. */
export const articlesByLanguage: Record<string, Article[]> = {
  "id": [
    a0,
  ],
  "en": [
    a1,
  ],
};
