/**
 * Authentication for the admin panel.
 *
 * One operator, one password. The password is never stored — only a scrypt
 * hash, generated by `npm run admin:password` and pasted into .env. Sessions
 * are stateless HMAC-signed cookies so the panel can restart without logging
 * anyone out and without a session store.
 *
 * This service is meant to sit behind your reverse proxy on HTTPS. Do not
 * expose it directly on a public port.
 */
import {
  createHmac,
  randomBytes,
  scryptSync,
  timingSafeEqual,
} from "node:crypto";

const SCRYPT = { N: 2 ** 15, r: 8, p: 1, keylen: 64 };
const SESSION_TTL_MS = 12 * 60 * 60 * 1000;
export const SESSION_COOKIE = "journal_admin";
export const CSRF_COOKIE = "journal_csrf";

/** `scrypt$N$r$p$saltB64$hashB64` */
export function hashPassword(password) {
  const salt = randomBytes(16);
  const hash = scryptSync(password, salt, SCRYPT.keylen, {
    N: SCRYPT.N,
    r: SCRYPT.r,
    p: SCRYPT.p,
    // scrypt needs room to work at this cost factor.
    maxmem: 256 * 1024 * 1024,
  });
  return [
    "scrypt",
    SCRYPT.N,
    SCRYPT.r,
    SCRYPT.p,
    salt.toString("base64"),
    hash.toString("base64"),
  ].join("$");
}

export function verifyPassword(password, stored) {
  try {
    const [scheme, N, r, p, saltB64, hashB64] = String(stored).split("$");
    if (scheme !== "scrypt") return false;

    const salt = Buffer.from(saltB64, "base64");
    const expected = Buffer.from(hashB64, "base64");
    const actual = scryptSync(password, salt, expected.length, {
      N: Number(N),
      r: Number(r),
      p: Number(p),
      maxmem: 256 * 1024 * 1024,
    });
    return timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

function sign(value, secret) {
  return createHmac("sha256", secret).update(value).digest("base64url");
}

export function createSession(secret) {
  const expires = Date.now() + SESSION_TTL_MS;
  const payload = String(expires);
  return `${payload}.${sign(payload, secret)}`;
}

export function verifySession(token, secret) {
  if (!token) return false;
  const index = token.lastIndexOf(".");
  if (index < 1) return false;

  const payload = token.slice(0, index);
  const provided = Buffer.from(token.slice(index + 1));
  const expected = Buffer.from(sign(payload, secret));

  if (provided.length !== expected.length) return false;
  if (!timingSafeEqual(provided, expected)) return false;

  const expires = Number(payload);
  return Number.isFinite(expires) && expires > Date.now();
}

export function createCsrfToken() {
  return randomBytes(24).toString("base64url");
}

export function csrfMatches(cookieToken, formToken) {
  if (!cookieToken || !formToken) return false;
  const a = Buffer.from(String(cookieToken));
  const b = Buffer.from(String(formToken));
  return a.length === b.length && timingSafeEqual(a, b);
}

export function parseCookies(header = "") {
  const jar = {};
  for (const part of header.split(";")) {
    const index = part.indexOf("=");
    if (index < 1) continue;
    jar[part.slice(0, index).trim()] = decodeURIComponent(
      part.slice(index + 1).trim(),
    );
  }
  return jar;
}

export function cookie(name, value, { maxAge, secure }) {
  const attributes = [
    `${name}=${encodeURIComponent(value)}`,
    "Path=/",
    "HttpOnly",
    "SameSite=Strict",
    `Max-Age=${maxAge}`,
  ];
  if (secure) attributes.push("Secure");
  return attributes.join("; ");
}

/**
 * Fixed-window throttle on failed logins, keyed by client address. Small and
 * in-memory on purpose: one operator, one box.
 */
export function createLoginThrottle({ limit = 8, windowMs = 15 * 60 * 1000 } = {}) {
  const attempts = new Map();

  return {
    blocked(key) {
      const entry = attempts.get(key);
      if (!entry) return false;
      if (Date.now() > entry.resetAt) {
        attempts.delete(key);
        return false;
      }
      return entry.count >= limit;
    },
    fail(key) {
      const entry = attempts.get(key);
      if (!entry || Date.now() > entry.resetAt) {
        attempts.set(key, { count: 1, resetAt: Date.now() + windowMs });
        return;
      }
      entry.count += 1;
    },
    succeed(key) {
      attempts.delete(key);
    },
  };
}
